---
title: "data cleaning"
author: "chenyu jiang"
date: "2024-10-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data cleaning

```{r}
rm(list=ls())
data <- read.csv("BodyFat.csv")
# find the wrong line of BMI
# first turn the units of weight and height
data$WEIGHT_kg <-data$WEIGHT * 0.453592  # Convert the unit of weight to kilograms
data$HEIGHT_m <-data$HEIGHT * 0.0254 # Convert  the unit of height to meters
data$ADIPOSITY_calculated <- data$WEIGHT_kg / (data$HEIGHT_m ^2)

# Identify mismatches where calculated BMI and provided BMI are not within the tolerance
tolerance <- 0.1
data$mismatch <- abs(data$ADIPOSITY_calculated - data$ADIPOSITY) > tolerance

# Print the rows with mismatches
mismatches <- data[data$mismatch, ]
print(mismatches)
#correct the height_m
incorrect_rows <- which(data$mismatch == TRUE)
data_clean <- data
data_clean$HEIGHT_m[incorrect_rows] <- sqrt(data_clean$WEIGHT_kg[incorrect_rows]/data_clean$ADIPOSITY[incorrect_rows])
print(data_clean[incorrect_rows,])
```

$BMI=\frac{weight(kg)}{height(m)^2}$


```{r}
# find the wrong data of body fat and correct it with density
wrong_bodyfat <- data[data$BODYFAT < 5,]
wrong_bodyfat$correct_bodyfat <- (495/wrong_bodyfat$DENSITY) - 450
print(wrong_bodyfat)
#but we can see the data are bad, so we use another formula from wikipedia
wrong_bodyfat$correct_bodyfat_bmi <- (1.2*wrong_bodyfat$ADIPOSITY) +(0.23*wrong_bodyfat$AGE) - 5.4 -10.8
```

$\text{percent body fat from Siri equation: }PBF = \frac{495}{Density}-450$
$ \text{Adult body fat percentage} = (1.2 \times \text{BMI}) + (0.23 \times \text{age}) -(10.8 \times \text{sex})-5.4) \text{where sex is 0 for females and 1 for males}$


```{r}
data_clean2 <- data_clean[, !(names(data_clean) %in% c("WEIGHT", "HEIGHT","ADIPOSITY_calculated","mismatch"))]
wrong_inbodyfat <- which(data$BODYFAT < 5)
data_clean2$BODYFAT[wrong_inbodyfat] <- (1.2*data$ADIPOSITY[wrong_inbodyfat]) +(0.23*data$AGE[wrong_inbodyfat]) - 5.4 - 10.8
```


```{r}
data_use <- data_clean2[, !(names(data_clean2) %in% c("IDNO","DENSITY","BODYFAT"))]
colnames(data_use)[14] <- "HEIGHT"
colnames(data_use)[13] <- "WEIGHT"
data_use$WEIGHT <- round(data_use$WEIGHT, 2)
data_use$HEIGHT <- round(data_use$HEIGHT, 2)
write.csv(data_use, "Final Cleaned Data",row.names = FALSE)
```

Model selection

One factor
```{r}
data_use1 <- data_clean2[, !(names(data_clean2) %in% c("IDNO","DENSITY"))]
data_use1$HEIGHT_cm <- data_use1$HEIGHT_m *100
data_use1 <- data_use1[, !(names(data_use1) %in% c("HEIGHT_m"))]
data_use_new <- data_use1
colnames(data_use_new)[14] <- "WEIGHT"
colnames(data_use_new)[15] <- "HEIGHT"
```

```{r}
results_new1 <- list()   # the result of every model
r_squared_new1 <- c()  # find the R^2 of every model
rmse_values_new1 <- c() # find the RMSE of every model
variables_new1 <- names(data_use_new)
variables_new1 <- variables_new1[variables_new1 != "BODYFAT"]
for (var in variables_new1) {
  formula <- as.formula(paste("BODYFAT ~  ", var))
  model <- lm(formula, data = data_use_new)
  predictions <- predict(model, data_use_new)
  actuals <- data_use_new$BODYFAT
  rmse <- sqrt(mean((actuals - predictions)^2))
  r_squared_new1[var] <- summary(model)$r.squared
  rmse_values_new1[var] <- rmse
  results_new1[[var]] <- summary(model)
}
sort(r_squared_new1)
sort(rmse_values_new1)
```



Two factors
```{r}
# find R^2 and RMSE of all two factors model(one is ABDOMEN,and try one of the remaining factors.)
results_new2 <- list()   # the result of every model
r_squared_new2 <- c()  # find the R^2 of every model
rmse_values_new2 <- c() # find the RMSE of every model
variables_new2 <- names(data_use_new)
variables_new2 <- variables_new2[variables_new2 != "BODYFAT"]
variables_new2 <- variables_new2[variables_new2 != "ABDOMEN"]
for (var in variables_new2) {
  formula <- as.formula(paste("BODYFAT ~ ABDOMEN + ", var))
  model <- lm(formula, data = data_use_new)
  predictions <- predict(model, data_use_new)
  actuals <- data_use_new$BODYFAT
  rmse <- sqrt(mean((actuals - predictions)^2))
  r_squared_new2[var] <- summary(model)$r.squared
  rmse_values_new2[var] <- rmse
  results_new2[[var]] <- summary(model)
}
sort(r_squared_new2)
sort(rmse_values_new2)
```
Robustness Test

```{r}

#take 4 randomly selected points from the cleaned data set, get the model predictions, then compare with US Navy Method result

set.seed(1) #set seed to ensure reproducibility
test_set <- data_use_new[sample(nrow(data_use_new),4),]

#Abdomen model:
ab_model <- lm("BODYFAT ~ ABDOMEN",data_use_new)
test_ab <- test_set$ABDOMEN*ab_model$coefficients[2] + ab_model$coefficients[1]


#Abdomen & Weight model:
ab_wt_model <- lm("BODYFAT ~ ABDOMEN + WEIGHT", data_use_new)
test_ab_wt <- test_set$ABDOMEN*ab_wt_model$coefficients[2] + ab_wt_model$coefficients[1] + test_set$WEIGHT*ab_wt_model$coefficients[3]

#Abdomen & Height model:
ab_ht_model <- lm("BODYFAT ~ ABDOMEN + HEIGHT", data_use_new)
test_ab_ht <- test_set$ABDOMEN*ab_ht_model$coefficients[2] + ab_ht_model$coefficients[1] + test_set$HEIGHT*ab_ht_model$coefficients[3]

#US Navy Method Results for test set, according to https://www.calculator.net/body-fat-calculator.html
test_prior_model <- c(28.2,17.9,21.0,20)

#prior model vs. abdomen model:
ab_ss <- sum((test_ab - test_prior_model)**2)

#prior model vs. abdomen and weight model:
ab_wt_ss <- sum((test_ab_wt - test_prior_model)**2)

#prior model vs abdomen and height model:
ab_ht_ss <- sum((test_ab_ht - test_prior_model)**2)

print(ab_ss)
print(ab_wt_ss)
print(ab_ht_ss)
```





Model Diagnostics 

```{r}
#fit the model
model<- lm(data_use_new$BODYFAT~data_use_new$ABDOMEN+data_use_new$WEIGHT)
predicted<- predict(model)
summary(model)   
par(xaxs="i",yaxs="i")
summary(lm(data_use_new$BODYFAT~predicted))
#calculate VIF values
library(car)
vif_values <- vif(model)
print(vif_values)

#Fitted vs Real plot

# Calculate the ±50% bounds
lower_bound_50percent <- predicted * 0.50
upper_bound_50percent <- predicted * 1.50  
percent_error <- abs((data_use_new$BODYFAT - predicted) / data_use_new$BODYFAT) * 100

# Determine colors based on the percentage error
colors <- ifelse(percent_error <= 20, "lightgreen", "lightblue")
par(mar = c(5, 15, 5, 5))
plot(predicted, data_use_new$BODYFAT,
     col = colors, pch = 19, 
     main = "Predictions vs. Actual: Abdomen+Weight",
     xlab = "Predicted BodyFat (%)", 
     ylab = "",
     las= 1,
     xlim = c(0, 50), ylim = c(0, 50))
mtext("Actual BodyFat (%)", side = 2, line = 4, las = 1) 
abline(0, 1, col = "blue", lty = 2)
# Add a legend
legend("topleft", legend = c("Within +/- 20%", "Outside +/- 20%","R_squared:0.69","+/-50% line"),
       col = c("lightgreen", "lightblue","white","lightgrey"), pch = 19)

# Plot the fitted vs. actual values
# Add the ±%50 lines
lines(predicted, lower_bound_50percent, col = "darkgrey", lty = 2, lwd = 2)  
lines(predicted, upper_bound_50percent, col = "darkgrey", lty = 2, lwd = 2)  
within_20_percent <- sum(percent_error <= 20)
cat("Number of points within 20% of the true value:", within_20_percent)

#residual plot
par(mar = c(5, 10, 5, 5)) 
plot(fitted(model),resid(model),main = "Residual plot of ABDOMEN+WEIGHT_kg",xlab="Fitted values(BodyFat(%))",ylab="",pch =19, las = 1,col="lightblue")
mtext("Residuals", side=2, line=3, las=1)
abline(h=0,col="darkgrey",lty=2)

```



